version: '2'
services:
  catalog:
    build: ../scs-demo-jquery/scs-demo-catalog-jquery
  order:
    build: ../scs-demo-jquery/scs-demo-order-jquery
  varnish:
    build: varnish
    links:
     - order
     - catalog
    ports:
     - "8081:8080"

